baseURL = "https://qwxlea.github.io/n2/"
languageCode = "en-us"
title = "My New Hugo Site"
theme="gar"
ignoreErrors = ["error-remote-getjson"]
publishdir="docs"

[params]
    exNumber = 25
    exText = "Years of Experienced"
    prNumber = 2500
    prText = "Project completed"
    hcNumber = 1500
    hcText = "Happy Customers"
    awNumber = 30
    awText = "Award Winning"

    address = "Krustpils iela 50a, Rīgā"
    phone = "+371 29485790"
    addressLink = "https://ul.waze.com/ul?place=EkNLcnVzdHBpbHMgaWVsYSA1MCwgTGF0Z2FsZXMgcHJpZWvFoXBpbHPEk3RhLCBSxKtnYSwgTFYtMTA1NywgTGF0dmlhIjASLgoUChIJm3_5OmzS7kYRQXaymzU9gf0QMioUChIJvejiZw3S7kYRhQh_MB5kovU&ll=56.90550650%2C24.21599450&navigate=yes"

    #socialShare = ["twitter", "facebook", "whatsapp", "email"]

[social]
  facebook              = "example"
  youtube               = ""
  whatsapp              = "123456"
#  instagram             = "example"
  twitter               = "example"
  skype                 = ""
  telegram              = "example"
  email                 = "example"
